const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={products:[],areas:[],cart:{},category:"الكل",search:"",step:1,mode:"delivery",payment:"cash",area:null,branch:"",name:"",phone:"",address:"",order:"W00001"};
const cats={"Basket":"السلال","Bowls":"الأطباق","Bowls with olive oil":"أطباق بزيت الزيتون","Bread":"الخبز","Cake":"الكيك","Chapati Section":"الشباتي","Dairy":"منتجات الألبان","Fatayer":"الفطائر","Frozen Section":"المجمدات","Gluten-free":"خالي من الجلوتين","Jam":"المربى","Juices":"العصائر","Organic Products":"منتجات عضوية","Protein bars":"ألواح البروتين","Ramadan products":"منتجات رمضان","Sprouted Chickpea chips":"شيبس الحمص المبرعم","Sweets & biscuits":"الحلويات والبسكويت","Toast and samoon":"التوست والصمون","Whole grain sweets":"حلويات الحبوب الكاملة","Za'ater":"الزعتر","diabetes and insulin resistance Products":"منتجات السكري ومقاومة الإنسولين","keto diet (Made with almond flour)":"منتجات الكيتو","olive oil":"زيت الزيتون","talbeenah":"التلبينة","منتجات مختارة":"منتجات مختارة"};
const branches=[{id:"hawalli",name:"فرع حولي",brand:"صحي ولذيذ للتجهيزات الغذائية",address:"حولي، شارع تونس، مجمع علي فهد الخالد، دور الميزانين",phone:"66906605 | 22085888"},{id:"yarmouk",name:"فرع اليرموك",brand:"مخبز التين والزيتون",address:"اليرموك، قطعة 2، شارع 2",phone:"22085889 | 65162277"},{id:"abu",name:"فرع أبو الحصانية",brand:"مطعم التين الطبيعي",address:"أبو الحصانية، مول 30",phone:"22085886 | 99176512"}];
const money=n=>`${Number(n).toFixed(3)} د.ك`;
const product=id=>state.products.find(p=>p.id===id);
const items=()=>Object.entries(state.cart).map(([id,q])=>({p:product(id),q})).filter(x=>x.p);
const count=()=>items().reduce((s,x)=>s+x.q,0);
const subtotal=()=>items().reduce((s,x)=>s+x.p.price*x.q,0);
const delivery=()=>state.mode==="delivery"&&state.area?state.area.price:0;
const total=()=>subtotal()+delivery();
function toast(t){$("#toast").textContent=t;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),1700)}
function qty(id,d){state.cart[id]=Math.max(0,(state.cart[id]||0)+d);if(!state.cart[id])delete state.cart[id];renderCartBar();renderProducts();if(!$("#checkoutModal").classList.contains("hidden"))renderCheckout()}
function renderCartBar(){const n=count();$("#headerCount").textContent=n;$("#cartBadge").textContent=n;$("#cartTotal").textContent=money(subtotal());$("#floatingCart").classList.toggle("hidden",!n)}
function renderCategories(){const map={};state.products.forEach(p=>map[p.category]=(map[p.category]||0)+1);$("#categories").innerHTML=`<button class="${state.category==="الكل"?"active":""}" data-cat="الكل">الكل <small>${state.products.length}</small></button>`+Object.entries(map).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<button class="${state.category===c?"active":""}" data-cat="${c.replace(/"/g,"&quot;")}">${cats[c]||c} <small>${n}</small></button>`).join("");$$("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderCategories();renderProducts()})}
function renderProducts(){const q=state.search.trim().toLowerCase();const list=state.products.filter(p=>(state.category==="الكل"||p.category===state.category)&&(!q||`${p.name} ${p.nameEn} ${p.description}`.toLowerCase().includes(q)));$("#resultTitle").textContent=state.category==="الكل"?"كل المنتجات":cats[state.category]||state.category;$("#resultCount").textContent=`${list.length} منتج`;$("#productGrid").innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${p.name}">${state.cart[p.id]?`<b class="in-cart">في السلة × ${state.cart[p.id]}</b>`:""}</div><div class="product-info"><small>${cats[p.category]||p.category}</small><h3>${p.name}</h3><p>${p.description||p.nameEn}</p><div class="product-foot"><strong>${money(p.price)}</strong><button data-add="${p.id}">إضافة +</button></div></div></article>`).join("");$$("[data-add]").forEach(b=>b.onclick=()=>{qty(b.dataset.add,1);toast("تمت إضافة المنتج")})}
function totals(){return `<div class="totals"><span>مجموع المنتجات <b>${money(subtotal())}</b></span>${delivery()?`<span>رسوم التوصيل <b>${money(delivery())}</b></span>`:""}<strong>الإجمالي <b>${money(total())}</b></strong></div>`}
function openCheckout(){if(!count())return;state.step=1;$("#checkoutModal").classList.remove("hidden");renderCheckout()}
function setSteps(){$$(".steps div").forEach((x,i)=>{x.classList.toggle("active",i+1===state.step);x.classList.toggle("done",i+1<state.step)})}
function renderCheckout(){setSteps();$("#steps").classList.remove("hidden");$("#checkoutTitle").textContent="إتمام الطلب";if(state.step===1){$("#checkoutBody").innerHTML=`<div class="cart-list">${items().map(({p,q})=>`<div class="cart-row"><img src="${p.image}"><div><h4>${p.name}</h4><strong>${money(p.price*q)}</strong></div><div class="qty"><button data-plus="${p.id}">+</button><span>${q}</span><button data-minus="${p.id}">${q===1?"×":"−"}</button></div></div>`).join("")}</div>${totals()}<button class="primary" id="next1">تأكيد ومتابعة</button>`;$$("[data-plus]").forEach(b=>b.onclick=()=>qty(b.dataset.plus,1));$$("[data-minus]").forEach(b=>b.onclick=()=>qty(b.dataset.minus,-1));$("#next1").onclick=()=>{state.step=2;renderCheckout()}}else if(state.step===2)renderDelivery();else renderPayment()}
function renderDelivery(){let content=state.mode==="delivery"?`<div class="form"><label>الاسم<input id="name" value="${state.name}" placeholder="اكتب الاسم الكامل"></label><label>رقم الهاتف<input id="phone" dir="ltr" inputmode="tel" value="${state.phone}" placeholder="9999 9999"></label><label class="full">المنطقة<div class="area-wrap"><input id="areaSearch" placeholder="${state.area?`${state.area.name} — ${money(state.area.price)}`:"ابحث واختر المنطقة"}"><div class="area-list hidden" id="areaList"></div></div>${state.area?`<small class="selected-area">تم اختيار ${state.area.name} — ${money(state.area.price)}</small>`:""}</label><label class="full">تفاصيل العنوان<textarea id="address" placeholder="القطعة، الشارع، المنزل والدور…">${state.address}</textarea></label></div>`:`<div class="branches">${branches.map(b=>`<button class="option ${state.branch===b.id?"selected":""}" data-branch="${b.id}"><span class="radio"></span><div><strong>${b.name}</strong><b>${b.brand}</b><small>${b.address}<br>${b.phone}</small></div></button>`).join("")}</div>`;$("#checkoutBody").innerHTML=`<div class="tabs"><button class="${state.mode==="delivery"?"active":""}" id="deliveryTab">🚚 توصيل</button><button class="${state.mode==="pickup"?"active":""}" id="pickupTab">⌂ استلام</button></div>${content}<div class="actions"><button class="secondary" id="back1">رجوع</button><button class="primary" id="next2">تأكيد ومتابعة</button></div>`;$("#deliveryTab").onclick=()=>{state.mode="delivery";renderDelivery()};$("#pickupTab").onclick=()=>{state.mode="pickup";renderDelivery()};$("#back1").onclick=()=>{state.step=1;renderCheckout()};$$("[data-branch]").forEach(b=>b.onclick=()=>{state.branch=b.dataset.branch;renderDelivery()});if(state.mode==="delivery"){$("#name").oninput=e=>state.name=e.target.value;$("#phone").oninput=e=>{state.phone=e.target.value.replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/[^\d+ ]/g,"");e.target.value=state.phone};$("#address").oninput=e=>state.address=e.target.value;$("#areaSearch").oninput=e=>{const q=e.target.value.trim();const list=state.areas.filter(a=>a.name.includes(q)).slice(0,14);$("#areaList").innerHTML=list.map(a=>`<button data-area="${a.name}"><span>${a.name}</span><b>${money(a.price)}</b></button>`).join("");$("#areaList").classList.toggle("hidden",!q);$$("[data-area]").forEach(b=>b.onclick=()=>{state.area=state.areas.find(a=>a.name===b.dataset.area);renderDelivery()})}}$("#next2").onclick=()=>{if(state.mode==="delivery"&&(!state.name.trim()||state.phone.replace(/\D/g,"").length<8||!state.area||!state.address.trim()))return toast("يرجى استكمال بيانات التوصيل");if(state.mode==="pickup"&&!state.branch)return toast("يرجى اختيار الفرع");state.step=3;renderCheckout()}}
function renderPayment(){$("#checkoutBody").innerHTML=`<div class="payments"><button class="option ${state.payment==="cash"?"selected":""}" data-pay="cash"><span class="radio"></span><div><strong>الدفع كاش</strong><small>الدفع عند استلام الطلب</small></div></button><button class="option ${state.payment==="online"?"selected":""}" data-pay="online"><span class="radio"></span><div><strong>الدفع أونلاين</strong><small>دفع إلكتروني آمن وسريع</small></div></button></div>${totals()}<div class="actions"><button class="secondary" id="back2">رجوع</button><button class="primary" id="finish">تأكيد الطلب</button></div>`;$$("[data-pay]").forEach(b=>b.onclick=()=>{state.payment=b.dataset.pay;renderPayment()});$("#back2").onclick=()=>{state.step=2;renderCheckout()};$("#finish").onclick=finish}
function finish(){const n=Number(localStorage.getItem("webOrderCounter")||1);state.order=`W${String(n).padStart(5,"0")}`;localStorage.setItem("webOrderCounter",n+1);$("#steps").classList.add("hidden");$("#checkoutBody").innerHTML=`<div class="loading-state"><div class="spinner"></div><h3>لحظة واحدة…</h3><p>نعتمد طلبك ونجهز رقم الفاتورة</p></div>`;setTimeout(success,1000)}
function success(){buildInvoice();$("#checkoutTitle").textContent="تم استلام الطلب";$("#checkoutBody").innerHTML=`<div class="success"><div class="check">✓</div><h3>تم استلام الطلب</h3><p>رقم الطلب</p><strong class="order-no">${state.order}</strong><div class="actions" style="width:min(380px,100%)"><button class="secondary" id="newOrder">العودة للمتجر</button><button class="primary" id="pdf">تحميل الفاتورة PDF</button></div></div>`;$("#newOrder").onclick=()=>{state.cart={};renderCartBar();$("#checkoutModal").classList.add("hidden")};$("#pdf").onclick=downloadPdf}
function buildInvoice(){const pickup=branches.find(b=>b.id===state.branch);$("#invoice").innerHTML=`<img src="logo.png"><h2>صحي ولذيذ للتجهيزات الغذائية</h2><p>الكويت، حولي، شارع تونس، مجمع علي فهد الخالد، دور الميزانين<br>66906605 | 22085888</p><hr><p>رقم الفاتورة: <b>#${state.order}</b> — ${new Date().toLocaleDateString("ar-KW")}</p><p><b>العميل: ${state.name||"عميل المتجر"}</b><br>${state.mode==="delivery"?`📍 ${state.area.name} - ${state.address}`:`🛍️ استلام من ${pickup?.name||""}`}<br>${state.payment==="cash"?"الدفع: كاش":"الدفع: أونلاين"}</p><table><thead><tr><th>الصنف</th><th>الكمية</th><th>السعر</th></tr></thead><tbody>${items().map(({p,q})=>`<tr><td>${p.name}</td><td>${q}</td><td>${money(p.price*q)}</td></tr>`).join("")}</tbody></table><div class="invoice-totals"><span>مجموع الأصناف <b>${money(subtotal())}</b></span>${delivery()?`<span>رسوم التوصيل <b>${money(delivery())}</b></span>`:""}<strong>الإجمالي <b>${money(total())}</b></strong></div><footer>شكراً لزيارتكم!<br><small>صحتك أغلى ما تملك، فتناول شيئاً صحياً.</small></footer>`}
async function downloadPdf(){toast("جاري تجهيز الفاتورة…");const canvas=await html2canvas($("#invoice"),{scale:2,backgroundColor:"#fff"});const{jsPDF}=window.jspdf,pdf=new jsPDF("p","mm","a4"),w=180,h=canvas.height*w/canvas.width;pdf.addImage(canvas.toDataURL("image/png"),"PNG",15,12,w,h);pdf.save(`invoice-${state.order}.pdf`)}
$("#searchInput").oninput=e=>{state.search=e.target.value;renderProducts()};$("#checkoutBtn").onclick=openCheckout;$("#cartSummary").onclick=openCheckout;$("#headerCart").onclick=openCheckout;$("#closeCheckout").onclick=()=>$("#checkoutModal").classList.add("hidden");
Promise.all([fetch("products.json").then(r=>r.json()),fetch("delivery-areas.json").then(r=>r.json())]).then(([p,a])=>{state.products=p;state.areas=a;renderCategories();renderProducts();renderCartBar()}).catch(()=>$("#productGrid").innerHTML='<div class="loading">تعذر تحميل البيانات. يجب رفع جميع الملفات مع index.html.</div>');
